import '../styles/globals.css';
import '../styles/Text.css';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';

import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';

export const UserContext = React.createContext();

export default function MyApp({ Component, pageProps }) {
  const breakpoints = {
    xs: 550,
    sm: 760,
    md: 1020,
    lg: 1270,
    xl: 1420,
    xxl: 1600,
  };
  const [windowSize, setWindowSize] = useState(0);

  useEffect(() => {
    function handleWindowResize() {
      setWindowSize(window.innerWidth);
    }
    if (typeof window !== 'undefined') {
      window.addEventListener('resize', handleWindowResize);
    }

    return () => {
      window.removeEventListener('resize', handleWindowResize);
    };
  }, []);

  return (
    <UserContext.Provider value={{ breakpoints, windowSize }}>
      <Navbar></Navbar>
      <p>{windowSize}</p>

      <Head>
        <title>Local</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Component {...pageProps} />
      <Footer></Footer>
    </UserContext.Provider>
  );
}
